[tool]

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
python_version = "3.12"
ignore_missing_imports = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.pylint]
good-names = "db"